name: inputs demo with secrets

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "Input 1"
        required: true
      input2:
        description: "pick a color"
        required: false
        default: "blue"
        choices:
          - red
          - green
          - blue
          - yellow
          - purple
          - orange
          - brown


env:
  one: "w1-env"
  two: "w2-env"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print all inputs
        run: |
          echo "input1: ${{ inputs.input1 }}"
          echo "input2: ${{ inputs.input2 }}"

      - name: print all env
        run: |
          echo "one: ${{ env.one }}"
          echo "two: ${{ env.two }}"
          echo "secret: ${{ secrets.SECRET_V1 }}"