# aws auth 
# terraform version 1.16.0
# terraform path terraform-2tier-ecs/infra


name: terraform-2tier-ecs

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      plan_apply_destroy:
        description: "Plan, Apply, or Destroy"
        type: choice
        required: true
        default: "plan"
        options:
          - plan
          - apply
          - destroy
      infra_path:
        description: "Path to the Terraform infrastructure"
        type: string
        required: true
        default: "terraform-2tier-ecs/infra"

      tf_version:
        description: "Terraform version"
        type: string
        required: true
        default: "1.16.0"


env:
  # TF_VERSION: 1.16.0
  # infra_path: terraform-2tier-ecs/infra
  infra_path: ${{ inputs.infra_path }}
  TF_VERSION: ${{ inputs.tf_version }}
  AWS_REGION: ap-south-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Initialize Terraform
        working-directory: ${{ env.infra_path }}
        run: terraform init

      - name: ${{ inputs.plan_apply_destroy }} Terraform
        working-directory: ${{ env.infra_path }}
        run: terraform ${{ inputs.plan_apply_destroy }}
