# aws auth 
# terraform version 1.16.0
# terraform path terraform-2tier-ecs/infra


name: terraform-2tier-ecs

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  TF_VERSION: 1.16.0
  PATH: terraform-2tier-ecs/infra
  AWS_REGION: ap-south-1

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Initialize Terraform
          working-directory: ${{ env.PATH }}
          run: terraform init

      - name: Plan Terraform
        working-directory: ${{ env.PATH }}
        run: terraform plan
